# Generated by Django 4.1.1 on 2022-09-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='subtitute',
        ),
    ]
