# Generated by Django 4.1.1 on 2022-09-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_subtitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='substitute',
            field=models.BooleanField(default=False),
        ),
    ]
